"""Limites anti-DoS pour preview document et validation inline (Epic 9)."""

MAX_PREVIEW_FLAG_STATES: int = 512
MAX_PREVIEW_REPUTATION_STATES: int = 256
MAX_PREVIEW_GAME_SYSTEMS_ATTRIBUTES: int = 64
MAX_PREVIEW_GAME_SYSTEMS_SKILLS: int = 128
MAX_PREVIEW_GAME_SYSTEMS_REPUTATION_VALUES: int = 256
MAX_PREVIEW_GAME_SYSTEMS_FACTION_TITLES: int = 64
MAX_VALIDATE_FLAG_REFERENCES_INLINE_NODES: int = 5000
